# Generated by Django 3.2.9 on 2022-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
